name: Update README

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust the Node.js version as needed

      - name: Run script to update README
        run: node update-readme.js # Adjust the path to your update-readme.js script

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with carousel"
          git push
